version: '3'
services:
  nginx-quiche:
    build: ./nginx-quiche
    restart: unless-stopped
    depends_on:
      - app-upload
    ports:
      - '${PUBLISH_PORT}:443/udp'
      - '${PUBLISH_PORT}:443'
    volumes:
      - ${NGINX_DATA}/nginx.conf:/usr/local/nginx/conf/nginx.conf
      # NOTE: Should set cert properly
      - ${NGINX_DATA}/fullchain.pem:/etc/ssl/certs/server.crt
      # NOTE: Should set key properly
      - ${NGINX_DATA}/privkey.pem:/etc/ssl/private/server.key
    networks:
      - docker-nginx-quiche
  app-upload:
    build: ./app_upload
    restart: unless-stopped
    networks:
      - docker-nginx-quiche

networks:
  docker-nginx-quiche:
    ipam:
      driver: default
      config:
        - subnet: "${DC_NETWORK}"
